### ISSUE TITLE
Docker Setup Guide for TeamFlow

### ISSUE THREAD

**Issue by pssr1183** [pssr1183/teamflow_sb#6]
**This issue outlines the steps to set up TeamFlow, a task management system, in a Docker environment using Spring Boot, PostgreSQL, and Redis. These instructions ensure a multi-container deployment with persistent data and a working cache layer.**

**Setup Steps**

**Prerequisites**  

- Install Docker and Docker Compose: `docker --version`, `docker-compose --version`.  
- Install Java 17+ and Maven:` java -version`,` mvn -version`.  

- Clone the repo: `git clone https://github.com/pssr1183/TeamFlow.git && cd TeamFlow.`

Build the Application  
Run:  
bash

`mvn clean package`

Generates: target/demo-0.0.1-SNAPSHOT.jar.

- Create Dockerfile  

File: Dockerfile  
dockerfile
```
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY target/demo-0.0.1-SNAPSHOT.jar /app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app.jar"]
```

Configure docker-compose.yml  
File: docker-compose.yml  
yaml

```
version: "3.8"
services:
  app:
    image: teamflow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test_db_2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Poorna@1210
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_SQL_INIT_MODE=always
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_CACHE_TYPE=redis
    platform: linux/amd64
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=test_db_2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Poorna@1210
    ports:
      - "5433:5432"
    command: ["bash", "-c", "docker-entrypoint.sh postgres & sleep 5 && psql -U $POSTGRES_USER -tc 'SELECT 1 FROM pg_database WHERE datname = \"$POSTGRES_DB\"' | grep -q 1 || psql -U $POSTGRES_USER -c 'CREATE DATABASE \"$POSTGRES_DB\";' && wait"]
    platform: linux/amd64
  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    platform: linux/amd64
volumes:
  postgres-data:
```

Start Docker  
```
Clear stale state:  
bash

docker-compose down -v

Run:  
bash

docker-compose up --build --force-recreate

Verify Setup  
Redis:  
bash

docker exec -it redis-container redis-cli ping  # Expect: PONG

Postgres:  
bash

docker exec -it demo3-db-1 psql -U postgres -d test_db_2 -c "\dt"  # List tables
```
